"""
================================================================================
FILE: cli_simulator.py
ROLE: The "What-If" Console
PURPOSE: This script provides a simple, interactive way to test the OncoPath 
         risk engine. It allows you to simulate a patient and see their 
         "Metastatic Heatmap" directly in the terminal.
         
LEARNING POINTS:
- SIMULATION: By changing one variable (e.g., adding a KRAS mutation), 
  you can see how the risk "ripples" through 21 different organs.
- DATA DRIVEN: Every number you see here is generated by an XGBoost model 
  trained on thousands of real MSK-MET patients.
================================================================================
"""

import requests
import os
from urllib.parse import urljoin

API_BASE_URL = os.getenv("ONCOPATH_API_BASE_URL", "http://127.0.0.1:8000").rstrip("/") + "/"
API_URL = urljoin(API_BASE_URL, "simulate")

def run_simulation(age, sex, site, code, mutations):
    payload = {
        "age": age,
        "sex": sex,
        "primary_site": site,
        "oncotree_code": code,
        "mutations": mutations
    }
    
    try:
        response = requests.post(API_URL, json=payload)
        if response.status_code == 200:
            return response.json()
        else:
            print(f"❌ API Error: {response.text}")
            return None
    except Exception as e:
        print(f"❌ Connection Error: Is the API running? ({e})")
        return None

def print_heatmap(data):
    print("\n" + "="*50)
    print(f" 🌡️  METASTATIC RISK HEATMAP: {data['primary_site']} Cancer")
    print(f"    Patient Age: {data['patient_age']}")
    print("="*50)
    
    risks = data['simulated_risks']
    # Sort by risk for better visualization
    sorted_risks = sorted(risks.items(), key=lambda x: x[1], reverse=True)
    
    for site, prob in sorted_risks:
        clean_site = site.replace('DMETS_DX_', '').replace('_', ' ').title()
        
        # Create a visual bar
        bar_len = int(prob * 30)
        bar = "█" * bar_len + "░" * (30 - bar_len)
        
        # Color coding (simulated with emojis)
        emoji = "🔴" if prob > 0.7 else "🟡" if prob > 0.4 else "🟢"
        
        print(f"{emoji} {clean_site:<20} | {bar} | {prob*100:>5.1f}%")
    
    print("="*50)

if __name__ == "__main__":
    # Example Simulation: 65 year old Male with Lung Adenocarcinoma
    # We toggle "TP53" and "KRAS" to see the impact.
    print("🔬 SIMULATING: High-Risk Genomic Profile (TP53+ KRAS+ FGA+)")
    
    mock_patient = {
        "age": 68,
        "sex": "Male",
        "primary_site": "Lung",
        "oncotree_code": "LUAD",
        "mutations": {}
    }
    
    # In this script, we assume the API is already running.
    print("\n> Querying the OncoPath Multi-Omic Engine...")
    
    results = run_simulation(
        mock_patient["age"], 
        mock_patient["sex"], 
        mock_patient["primary_site"], 
        mock_patient["oncotree_code"], 
        mock_patient["mutations"]
    )
    
    if results:
        print_heatmap(results)
    else:
        print("\n[TIP] Make sure the API is running in another terminal: 'python scripts/api_service.py'")
